<?php
declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Checkout\ViewModel\Checkout\AddressView;

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var AddressView $addressView */
/** @var Escaper $escaper */

$addressView = $viewModels->require(AddressView\AddressViewBilling::class);
?>
<div>
    <?= /* @noEscape */ $addressView->renderView() ?>
</div>
